global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: [ ]
      scheme: http
      timeout: 10s
      api_version: v1

scrape_configs:

## disabled to get host system logs
#  - job_name: system
#    static_configs:
#      - targets:
#          - localhost
#        labels:
#          job: varlogs
#          __path__: /var/log/*log
  - job_name: 'tgi'
    static_configs:
      - targets: [ 'tgi:80' ]

  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8899']

  # Example job for node_exporter
  - job_name: 'node-exporter'
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
    - targets: ['cadvisor:8080']

  - job_name: 'nvidia-smi-exporter'
    static_configs:
      - targets: [ 'obsrv-nvidia-smi-exporter:9835' ]


  - job_name: 'prometheus'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - localhost:9090


  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker_logs
          __path__: /var/lib/docker/containers/*/*-json.log