{
 "title": "TGI 2",
 "description": "These metrics are exposed by containers run using Hugging Face’s Text Generation Inference toolkit project (https://github.com/huggingface/text-generation-inference). \r\n\r\nThe second version is a simple dashboard displaying all available metrics, and the third version is an improved version based on the dashboard here: https://github.com/huggingface/text-generation-inference/discussions/1127#discussioncomment-7854661",
 "time": { "from": "now-3h", "to": "now-1m" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(tgi_request_count,instance)"
    }
   },
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(tgi_request_success{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(increase(tgi_request_failure{instance=~\"$instance\"}[$__rate_interval])) by (err)",
     "legendFormat": "Error: {{err}}"
    }
   ]
  },
  {
   "title": "Latency quantiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(tgi_request_duration_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(tgi_request_duration_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(tgi_request_duration_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "E2E Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(tgi_request_duration_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Number of replicas",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "count(tgi_request_count{instance=~\"$instance\"})",
     "legendFormat": "Replicas"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(tgi_queue_size{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency per token quantiles",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(tgi_request_mean_time_per_token_duration_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(tgi_request_mean_time_per_token_duration_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(tgi_request_mean_time_per_token_duration_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "E2E Latency per token",
   "type": "heatmap",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 10 },
   "targets": [
    {
     "expr": "sum(increase(tgi_request_mean_time_per_token_duration_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(tgi_queue_size{instance=~\"$instance\"})",
     "legendFormat": "Queue size"
    }
   ]
  },
  { "title": "Batching", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Batch Size",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "avg(tgi_batch_current_size{instance=~\"$instance\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Input length",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(tgi_request_input_length_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(tgi_request_input_length_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(tgi_request_input_length_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Generated Tokens",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(tgi_request_generated_tokens_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(tgi_request_generated_tokens_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(tgi_request_generated_tokens_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Max tokens per batch",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "avg(tgi_batch_current_max_tokens{instance=~\"$instance\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Queue quantiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(tgi_request_queue_duration_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(tgi_request_queue_duration_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(tgi_request_queue_duration_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Inference quantiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(tgi_request_inference_duration_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(tgi_request_inference_duration_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(tgi_request_inference_duration_bucket{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Concatenates",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "sum(increase(tgi_batch_concat{instance=~\"$instance\"}[$__rate_interval])) by (reason)",
     "legendFormat": "Reason: {{ reason }}"
    }
   ]
  },
  { "title": "Prefill & Decode", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Prefill Quantiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(tgi_batch_inference_duration_bucket{method=\"prefill\", instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(tgi_batch_inference_duration_bucket{method=\"prefill\", instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(tgi_batch_inference_duration_bucket{method=\"prefill\", instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Prefill Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(increase(tgi_batch_inference_duration_bucket{method=\"prefill\", instance=~\"$instance\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Decode quantiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(tgi_batch_inference_duration_bucket{method=\"decode\", instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (rate(tgi_batch_inference_duration_bucket{method=\"decode\", instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(tgi_batch_inference_duration_bucket{method=\"decode\", instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Decode Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "sum(increase(tgi_batch_inference_duration_bucket{method=\"decode\", instance=~\"$instance\"}[$__rate_interval])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Debug",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Forward quantiles",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(tgi_batch_forward_duration_bucket{method=\"decode\", instance=~\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le) (rate(tgi_batch_forward_duration_bucket{method=\"decode\", instance=~\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(tgi_batch_forward_duration_bucket{method=\"decode\", instance=~\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Forward Latency",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 6, "x": 6, "y": 55 },
     "targets": [
      {
       "expr": "sum(increase(tgi_batch_forward_duration_bucket{method=\"decode\", instance=~\"$instance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Token Decode quantiles",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(tgi_batch_decode_duration_bucket{method=\"decode\", instance=~\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le) (rate(tgi_batch_decode_duration_bucket{method=\"decode\", instance=~\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(tgi_batch_decode_duration_bucket{method=\"decode\", instance=~\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Token Decode Latency",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 55 },
     "targets": [
      {
       "expr": "sum(increase(tgi_batch_decode_duration_bucket{method=\"decode\", instance=~\"$instance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Filter Batch quantiles",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(tgi_batch_filter_duration_bucket{method=\"decode\", instance=~\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le) (rate(tgi_batch_filter_duration_bucket{method=\"decode\", instance=~\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(tgi_batch_filter_duration_bucket{method=\"decode\", instance=~\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Filter Batch Latency",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 6, "x": 6, "y": 66 },
     "targets": [
      {
       "expr": "sum(increase(tgi_batch_filter_duration_bucket{method=\"decode\", instance=~\"$instance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Batch Concat quantiles",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 6, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(tgi_batch_concat_duration_bucket{method=\"decode\", instance=~\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le) (rate(tgi_batch_concat_duration_bucket{method=\"decode\", instance=~\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(tgi_batch_concat_duration_bucket{method=\"decode\", instance=~\"$instance\"}[$__rate_interval])))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Batch Concat latency",
     "type": "heatmap",
     "gridPos": { "h": 11, "w": 6, "x": 18, "y": 66 },
     "targets": [
      {
       "expr": "sum(increase(tgi_batch_concat_duration_bucket{method=\"decode\", instance=~\"$instance\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  }
 ]
}